apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: c2hvcF9pbnZhZGVy
  mongo-root-password: dG90bw==
# shop_invader  toto
# mongodb://shop_invader:toto@mongodb-service:27017