apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 27017
    protocol: TCP
    name: mongodb-service
  - port: {{ .Values.service.expressPort }}
    targetPort: 8081
    protocol: TCP
    name: mongo-express-service
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
