apiVersion: v1
kind: Secret
metadata:
  name: shopinvader-secret
type: Opaque
data:
  SECRET_KEY_BASE: NDlhNzliNWVkNmMzN2NjY2UyYzA1ZTY4M2JkZWIwMjE0NWE3MjljZjEwN2Q0YTMxOTgxM2E0MjRhM2YyYTZkM2Y3MTljZGExYzVhYWYzNDg4MDA4MGUzNDQwOGI2MDUyZGVjMTY4ZThhYWNmNDhhNzc1ZWYyNmJlNjQyZWMyMTQK
  DRAGON_FLY_SECRET: ZWQwYjZiOTI0ZGU1NGY4MDM5MjJhNjdjOWJlNTQ5ZmY3ZTQ5YTAxNTkwZjQwYjdmOGEwZmZhNzE2NDU0ZjY2ODg5NzIyOGE5OWI3ZTFhMGM5NDY5NzZjODQ4ZjhhMTk5NTI4YjM5MGFmZGNjZjRiZjI0OGRmNjZkMGVhYzE4NWYK
  DEVISE_PEPPER: TGEgdmllIGVuIHJvc2UK
  mongo-root-uri: bW9uZ29kYjovL3Nob3BfaW52YWRlcjp0b3RvQG1vbmdvZGItc2VydmljZToyNzAxNwo=

