apiVersion: v1
kind: ConfigMap
metadata:
  name: shopinvader-config
data:
  {{- if .Values.shopinvader.StoreAssetInS3 }}
  STORE_ASSET_IN_S3: {{ .Values.shopinvader.StoreAssetInS3 | quote }}
  S3_CACHE_CONTROL: {{ .Values.shopinvader.S3CacheControl | quote }}
  {{- end }}
  {{- if .Values.shopinvader.S3BucketRegion }}
  S3_BUCKET_REGION: {{ .Values.shopinvader.S3BucketRegion }}
  {{- end }}
  {{- if .Values.shopinvader.CdnHostUrl }}
  CDN_ASSET_HOST: {{ .Values.shopinvader.CdnHostUrl }}
  {{- end }}
  RAILS_ENV: {{ .Values.shopinvader.RailsEnv | quote }}
  RAILS_SERVE_STATIC_FILES: {{ .Values.shopinvader.RailsServeStaticFiles | quote }}
  LOCOMOTIVE_ENABLE_REGISTRATION: {{ .Values.shopinvader.LocomotiveEnableRegistration | quote }}
  LOCOMOTIVE_ADMIN_SSL_REDIRECT: {{ .Values.shopinvader.LocomotiveAdminSslRedirect | quote }}

