{{- $svcName := include "shopinvader.fullname" . }}
{{- with .Values.ingressRouteClient }}
{{- $match := printf "Host(`%s`)" ( join "`) || Host(`" .hosts ) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shopinvader-cert
spec:
  secretName: shopinvader-tls
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ $.Values.issuerRef }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shopinvader-ingressroute-client
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $.Values.rateLimit.paths }}
    - match: {{ printf "(%s) && Path(`%s`)" $match . | quote }}
      kind: Rule
      middlewares:
        - name: shopinvader-ratelimit
        - name: redirect-https
        {{- if $.Values.waf.enabled }}
        - name: waf-authforward
        {{- end }}
      services:
        - name: {{ $svcName }}
          port: 80
    {{- end }}
    - match: {{ printf "(%s) && PathPrefix(`%s`)" $match .pathPrefix | quote }}
      kind: Rule
      middlewares:
        - name: redirect-https
        {{- if $.Values.waf.enabled }}
        - name: waf-authforward
        {{- end }}
      services:
        - name: {{ $svcName }}
          port: 80
      priority: 1
  tls:
    secretName: shopinvader-tls
{{- end }}
