apiVersion: v1
kind: Secret
metadata:
  name: s3-storage-secret
type: Opaque
data:
  {{- if .Values.shopinvader.StoreAssetInS3 }}
  root-user: {{ .Values.shopinvader.secrets.S3_KEY_ID }}
  root-password: {{ .Values.shopinvader.secrets.S3_SECRET_KEY | quote }}
  {{- end }}