apiVersion: v1
kind: Secret
metadata:
  name: shopinvader-secret
type: Opaque
data:
{{- with .Values.shopinvader.secrets }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
{{- end }}
