apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopinvader.fullname" . }}
  labels:
    {{- include "shopinvader.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "shopinvader.selectorLabels" . | nindent 4 }}
