apiVersion: v1
kind: Service
metadata:
  name: shopinvader-service
  labels:
    {{- include "shopinvader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: shopinvader-service
  selector:
    {{- include "shopinvader.selectorLabels" . | nindent 4 }}
