
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      name: client
      targetPort: 9200
    - port: {{ .Values.service.nodePort }}
      name: nodes
      targetPort: 9300
    - port: {{ .Values.service.kibanaPort }}
      name: kibana
      targetPort: 5601
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}